---
apiVersion: v1
kind: Namespace
metadata:
  name: dev-ns
  labels:
    name: dev-ns

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
  namespace: dev-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodeapp
  template:
    metadata:
      labels:
        app: nodeapp
    spec:
      containers:
        - name: node
          image: gcr.io/ITI-1/nodejs:latest
          ports:
            - name: app
              containerPort: 3000


---


apiVersion: v1
kind: Service
metadata:
  name: load-balancer
  namespace: dev-ns
spec:
  type: LoadBalancer
  selector:
    app: nodeapp
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000